apiVersion: v1
kind: Service
metadata:
  name: aws-dns-bind
  labels:
    app: aws-dns-bind
spec:
  type: ClusterIP
  selector:
    app: aws-dns-bind
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: 53
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53
